# Generated by Django 2.2.12 on 2020-08-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('kantor', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=200)),
                ('deskripsi_singkat', models.TextField()),
                ('deskripsi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
