# Generated by Django 2.2.12 on 2020-08-10 08:26

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobsPortal', '0002_auto_20200810_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='judul'),
        ),
    ]
