# Generated by Django 2.2.12 on 2020-08-25 09:02

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobsPortal', '0008_auto_20200824_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=slugger.fields.AutoSlugField(blank=True, populate_from='judul', unique=True),
        ),
    ]
