# Generated by Django 2.2.12 on 2020-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsPortal', '0009_auto_20200825_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamaran',
            name='status',
            field=models.CharField(default='belum dilihat', max_length=200),
        ),
    ]
